### ISSUE TITLE
No footstep sound on road street and sidewalk

### ISSUE THREAD

**Issue by CurlySparkle** [ZPSNMRiHIssues/nmrihissues#509]
It seems theres no playing footstep sound on these two textures for some reason, must be an glitch or bug on the vmt files, the following video will show this issue about, its not a big problem, but just to let know for fix this someday for the next update.

http://youtu.be/f3HLcW7AQY0

i hope im not the only one that has this problem.

**Comment by Bucky20** [comment]
Materials now have sound. Checking through other materials with _wet in them to make sure they do not have the same problem.
