### ISSUE TITLE
Certain Textures Don't Appear

### ISSUE THREAD

**Issue by AFuzzyCat** [ZPSNMRiHIssues/nmrihissues#573]
A few weeks ago I got on steam and it said that the game had updated and I kept playing like normal. Until I played nmo_junction and the church map when textures were appearing pink purple and black. 
![2014-05-03_00001](https://cloud.githubusercontent.com/assets/7549478/2938682/4efd36d0-d91b-11e3-9363-86b1752d49ce.jpg)
![2014-05-03_00002](https://cloud.githubusercontent.com/assets/7549478/2938685/53cd22f6-d91b-11e3-9d60-b45ad65783cf.jpg)
![2014-05-11_00001](https://cloud.githubusercontent.com/assets/7549478/2938686/592a2e42-d91b-11e3-8349-2ef1bbd69a66.jpg)

Can anyone help me with this problem? I don't want to uninstall my game and re-install it because that will take around a day or two.

**Comment by Bucky20** [comment]
Specular issue. Everything looks to be correct on our end. Might need to verify game cache.
