### ISSUE TITLE
Missing texture in voice options menu

### ISSUE THREAD

**Issue by Wazanator** [ZPSNMRiHIssues/nmrihissues#647]
![2014-10-29_00007](https://cloud.githubusercontent.com/assets/2752911/4836206/9e1bd60a-5fc0-11e4-91f9-44b0edb02ef0.jpg)

Just noticed there is a texture missing in the voice options menu

Build: 1.09 beta

**Comment by Bucky20** [comment]
Do we know the original location of where this should be? Must have been deleted since it was not custom. Or was never there to begin with.

**Comment by Bucky20** [comment]
Will be going under voice/voice_menu. Committed the texture. Waiting for res file.
