### ISSUE TITLE
Select Fire (NMRiH Dev Build)

### ISSUE THREAD

**Issue by DemolitionSteve** [ZPSNMRiHIssues/nmrihissues#669]
On nmo_emergency (2/1/15) I was only able to change the fire mode on the M16 once, to set it to burst. I was unable to change the fire mode back to single fire, and was unable to select a fire mode at all for the MP5, and had Riley equip an MP5 an change it, so they could drop it for me. Once equipped with the new MP5, it was successfully changed to burstfire, but I was unable to change it to any other fire mode. Other clients in the server were able to freely change their fire modes, but I specifically was not able to, save for the first initial time with the M16.

**Comment by Smil3yRiley** [comment]
Make sure your weapon scripts are all up to date (delete the scripts folder and svn update) and when you're in the game, open up dev console and type the following into console

bind x +selectfire

**Comment by Smil3yRiley** [comment]
fixed revision 8206
