### ISSUE TITLE
(code) White Outline on screen from adding html panel

### ISSUE THREAD

**Issue by Smil3yRiley** [ZPSNMRiHIssues/nmrihissues#670]
We added an entity which will allow mappers to display html windows when triggered (notes for people to read, etc.) and the VGUI panel it's on is causing a noticeable white border visual effect to occur on the screen.

Posting this as a reminder for Rocky!

**Comment by 2ndClassCitizen** [comment]
![2015-02-05_00001](https://cloud.githubusercontent.com/assets/4022172/6072949/d617390c-ad75-11e4-83e8-65d019320c4f.jpg)
