### ISSUE TITLE
Various Misc Things on nmo_fema and nmo_brookyln

### ISSUE THREAD

**Issue by DemolitionSteve** [ZPSNMRiHIssues/nmrihissues#674]
- On nmo_brooklyn, the skybox does not appear to render while looking through the scope of the M16. Unconfirmed if this applies to any other weapons.
![2015-02-05_00002](https://cloud.githubusercontent.com/assets/6455381/6072762/5669e198-ad73-11e4-8d6f-49e4d33c2434.jpg)

- On nmo_fema, by the dead soldier in the hallway (really narrows it down, I know), you can see through the floor
![2015-02-05_00008](https://cloud.githubusercontent.com/assets/6455381/6072771/70667da4-ad73-11e4-9d04-6a25ea63b803.jpg)

- On nmo_fema, the collapsed cots and sleeping arrangements are easily walk over-able, but this one ceases all player motion once hit
![2015-02-05_00005](https://cloud.githubusercontent.com/assets/6455381/6072779/89555b64-ad73-11e4-9402-faae750aeaa3.jpg)

**Comment by Smil3yRiley** [comment]
I can't say about the first issue (I already submitted it as a separate ticket at #672 but the rest are fixed
