### ISSUE TITLE
Low res - can't see code

### ISSUE THREAD

**Issue by 2ndClassCitizen** [ZPSNMRiHIssues/nmrihissues#676]
On maps where a computer needs to be accessed to read the code on the screen (brooklyn, junction) if your texture resolution is set to the lowest setting, the numbers become illegible. You can't make out anything. Please improve the texture resolution on the screen, or something, so we can see the code.

**Comment by Smil3yRiley** [comment]
![2015-02-05_00011](https://cloud.githubusercontent.com/assets/3606650/6073020/5f1ccfb2-ad6e-11e4-8b6e-1d5968051012.jpg)

This specific computer model's the one with the problem.

**Comment by Bucky20** [comment]
Has then been fixed? Do we know what the filepath for the material is?

**Comment by Smil3yRiley** [comment]
Correction, it's the cj_comp_newmonitor_objective.mdl under models/props/objectives, textures are under materials/models/gmn (they're all the code related .vtfs)

**Comment by Bucky20** [comment]
Removed mipmaps from textures named CJ_Computers, cj_objective_code-12, cj_objective_desktop, cj_objective_login. Should resolve texture quality on low settings.

**Comment by Smil3yRiley** [comment]
Can confirm that it's fixed on my end, and Bucky confirms that the fix works

Closing ticket
