### ISSUE TITLE
Item_bandage missing from item wheel on pickup

### ISSUE THREAD

**Issue by Wazanator** [ZPSNMRiHIssues/nmrihissues#682]
Picking up bandages does not display them in the item wheel.

![2015-02-08_00001](https://cloud.githubusercontent.com/assets/2752911/6100217/86f75c96-afd0-11e4-9e5b-6c98a04901b8.jpg)
![2015-02-08_00002](https://cloud.githubusercontent.com/assets/2752911/6100216/86f6cb3c-afd0-11e4-9303-fcbb4e1b25d4.jpg)
![2015-02-08_00003](https://cloud.githubusercontent.com/assets/2752911/6100218/86f914e6-afd0-11e4-9964-cf0b9c665603.jpg)

**Comment by Smil3yRiley** [comment]
fixed in r8212
