### ISSUE TITLE
Chinatown - Glitched Route to avoid gate objective

### ISSUE THREAD

**Issue by ThoughTMusic** [ZPSNMRiHIssues/nmrihissues#694]
While on the street directly in front of the gate objective in Chinatown, you can walk on the elevated debris where the wall blocks the street before the T intersection (T intersection is past the barricade that blocks the street and not meant for players to go there). If you get a zombie close enough, you can hop on their head then get on that barricade. From there, you can follow the buildings using ledges, and hop over the fence and avoid the gate objective. It needs a clip texture to block that.

![2015-03-17_00001](https://cloud.githubusercontent.com/assets/11540884/6712066/b01271e2-cd58-11e4-99a0-cff699c87301.jpg)
![2015-03-17_00002](https://cloud.githubusercontent.com/assets/11540884/6712063/b0113fd4-cd58-11e4-8e83-40a513e006db.jpg)
![2015-03-17_00003](https://cloud.githubusercontent.com/assets/11540884/6712064/b011d7f0-cd58-11e4-8603-8305aaf0b92c.jpg)
![2015-03-17_00004](https://cloud.githubusercontent.com/assets/11540884/6712065/b01265b2-cd58-11e4-8400-4d5953faf2c6.jpg)
![2015-03-17_00005](https://cloud.githubusercontent.com/assets/11540884/6712067/b012f8ce-cd58-11e4-874d-45f4e243f928.jpg)

**Comment by Smil3yRiley** [comment]
Should be fixed in r8294
