### ISSUE TITLE
nms_midtown zfighting bug on door

### ISSUE THREAD

**Issue by Wazanator** [ZPSNMRiHIssues/nmrihissues#695]
![2015-03-18_00002](https://cloud.githubusercontent.com/assets/2752911/6719224/2828b2a8-cd87-11e4-9cf7-00d3b74f5c61.jpg)

Zfighting issue on this doorway (the two metal strips and the wood)

**Comment by billionlioe** [comment]
you mean the clipping right? (author here)

**Comment by billionlioe** [comment]
Fixed as of r8289
