### ISSUE TITLE
[MAC]  Spectator Free Look (it prevents from using keyboard)

### ISSUE THREAD

**Issue by 2STRONKY** [ZPSNMRiHIssues/nmrihissues#698]
Hi NHRIH team,

problem : the spectators controls menu prevents you from using the keyboard and there is no free look and sometimes mouse freezes (sometimes clickin with mouse1 cycles the different views, sometimes doesnt )

ESC button is the only one button on whole kboard works.
the only thing i can do to get out of the HUD its disconnect from server and reconnect or just wait the respawn.

 known bug  :
http://steamcommunity.com/app/224260/discussions/0/684839199850620989/

ps i've joined "NMRiH Beta Survivor nmrihbs" group and i offer myself as mac user volounter tester.

stem account  : http://steamcommunity.com/id/2stronky 
thanks in advance

**Comment by AtheistNMRiH** [comment]
Try press Tab 2 times and then Crouch button

**Comment by 2STRONKY** [comment]
Hi, i tried it..but the only result its that it enlights in orange the selections "free view" (right side down) then still nothing.

**Comment by AtheistNMRiH** [comment]
Press Tab, until u will not see light in orange and then Crouch button

**Comment by Bubka3** [comment]
This is probably a source engine bug and not really fixable by us. If you mash the CTRL key enough times it should let you out. Eventually.

**Comment by 2STRONKY** [comment]
@AtheistNMRiH "Press Tab, until u will not see light in orange and then Crouch button" did it but doesnt do nothing. 
@Bubka3 yes i tryed it too but still wont work.
i will try to bind it in a different key..

btw the light in orange works only in windowed mode, in full screen wont work.

thx a lot for the fast reply.

keep up the great work, after decades of years playng Q3A coulndt find a game that makes me addict for ages....NMRiH did it.
hope to see you in game see ya
