### ISSUE TITLE
Nmo_brooklyn map bugs

### ISSUE THREAD

**Issue by Fersigal** [ZPSNMRiHIssues/nmrihissues#707]
Car bugs:
![2015-03-28_00050](https://cloud.githubusercontent.com/assets/11538773/6880330/bbcc2bd8-d52b-11e4-84c0-090ae429384e.jpg) Zombie Blocking the car from being pushed, the zombies froze for some reason but better example is if they get stuck when you almost pushed the car at the wall
![2015-03-28_00051](https://cloud.githubusercontent.com/assets/11538773/6880331/bbce4da0-d52b-11e4-8da5-8d2009612b49.jpg) You can push the car backwards (drag) if you go by the sides and then go at the back)

Fire bugs:
![2015-03-28_00044](https://cloud.githubusercontent.com/assets/11538773/6880325/bbb66c26-d52b-11e4-9bb6-5be73a29bc6e.jpg) Fire bug (you won't receive any dmg)
![2015-03-28_00046](https://cloud.githubusercontent.com/assets/11538773/6880326/bbb73a20-d52b-11e4-9d5d-6ca1ae6a3bd1.jpg) Fire Bug, you can also get between the gap of the red car and the green one

Collision Bugs:
![2015-03-28_00001](https://cloud.githubusercontent.com/assets/11538773/6880286/bb21cf62-d52b-11e4-8f1a-1982746b18a8.jpg) You can only shoot through it with SW or Sniper rifle 

Other Bugs:
![2015-03-28_00021](https://cloud.githubusercontent.com/assets/11538773/6880300/bb5afdbe-d52b-11e4-96c6-13e6b4591032.jpg) Can get stuck after shower part
![2015-03-28_00047](https://cloud.githubusercontent.com/assets/11538773/6880327/bbb7cddc-d52b-11e4-8716-bbce47c5d056.jpg) Untextured bug (at the fire thingy)
![2015-03-28_00055](https://cloud.githubusercontent.com/assets/11538773/6880335/bbe0e5dc-d52b-11e4-9a22-16045577d970.jpg) You can Axtinguish from upside the car without being hit
![2015-03-28_00056](https://cloud.githubusercontent.com/assets/11538773/6880336/bbe2db12-d52b-11e4-91e0-eb5df9cd625d.jpg) You can go under the truck
![2015-03-28_00061](https://cloud.githubusercontent.com/assets/11538773/6880400/25cf24dc-d530-11e4-9cdb-0218852879f1.jpg) If you go through the window of the office and someone opens the gate and he dies after he recently respawned you can go upside and go downside then. He will respawn again
![2015-03-28_00067](https://cloud.githubusercontent.com/assets/11538773/6880406/25e68758-d530-11e4-914d-cde5814ec0ff.jpg) Classic gate bug i posted before
![2015-03-28_00069](https://cloud.githubusercontent.com/assets/11538773/6880410/25ecd680-d530-11e4-875c-482a4825a264.jpg) You can go through the fence by 1 seconds before it's even pulled off 
![2015-03-28_00073](https://cloud.githubusercontent.com/assets/11538773/6880413/25fed4ca-d530-11e4-84e8-a9581e123b8f.jpg) You can go by the right side and still push the cart
![2015-03-28_00003](https://cloud.githubusercontent.com/assets/11538773/6880288/bb2c0284-d52b-11e4-9415-71a19af022e7.jpg) unable to get the key
![2015-03-28_00004](https://cloud.githubusercontent.com/assets/11538773/6880287/bb2922e4-d52b-11e4-82c4-ae1add97aed9.jpg) you can pick up your gun a while after your death and drop it if you keep doing this before you died, when dead cam appears this is not possible anymore
![2015-03-28_00010](https://cloud.githubusercontent.com/assets/11538773/6880291/bb2f39cc-d52b-11e4-8c69-9256c7213082.jpg) unable to get the key
![2015-03-28_00012](https://cloud.githubusercontent.com/assets/11538773/6880293/bb40719c-d52b-11e4-8058-2ec1e3b46c32.jpg) Zombies will gather up at the window when you stay there (weird interaction though)
![2015-03-28_00013](https://cloud.githubusercontent.com/assets/11538773/6880294/bb4145e0-d52b-11e4-9a7f-ea972ddfe73a.jpg) Items can get stuck after the vending machine
![2015-03-28_00017](https://cloud.githubusercontent.com/assets/11538773/6880297/bb46a8c8-d52b-11e4-9934-add6a054e6a2.jpg) Zombies will not be interested in you if you stay on the ledge above the vending machine (not on the vending machine but on the ledge)
![2015-03-28_00070](https://cloud.githubusercontent.com/assets/11538773/6880408/25ebc72c-d530-11e4-89e7-3c7ee0768447.jpg) You can go from the army car to the liquor and then go at the firestairs
![2015-03-28_00071](https://cloud.githubusercontent.com/assets/11538773/6880409/25ec5ff2-d530-11e4-8a47-4c339d95f464.jpg) You can get easily up the gate 
![2015-03-28_00072](https://cloud.githubusercontent.com/assets/11538773/6880412/25f09f7c-d530-11e4-8431-7abba627dd90.jpg) Also easy to get off 
Invulnerable bugs: 
![2015-03-28_00028](https://cloud.githubusercontent.com/assets/11538773/6880308/bb732592-d52b-11e4-8f08-d6fa964756aa.jpg)
![2015-03-28_00009](https://cloud.githubusercontent.com/assets/11538773/6880290/bb2e8d06-d52b-11e4-85dc-6926d1fec305.jpg)
![2015-03-28_00015](https://cloud.githubusercontent.com/assets/11538773/6880295/bb430ff6-d52b-11e4-8bbb-78f4dfdb98d8.jpg) You can get hit here but not on the next image
![2015-03-28_00016](https://cloud.githubusercontent.com/assets/11538773/6880296/bb44ae56-d52b-11e4-8b47-7e271ecf8400.jpg) 

![2015-03-28_00018](https://cloud.githubusercontent.com/assets/11538773/6880298/bb4ce9b8-d52b-11e4-9745-096fd651fdca.jpg) 
![2015-03-28_00020](https://cloud.githubusercontent.com/assets/11538773/6880299/bb590c8e-d52b-11e4-8a32-828bf59df234.jpg) You can get up the lockers from  the bench if you crouch jump onto it 
![2015-03-28_00019](https://cloud.githubusercontent.com/assets/11538773/6880301/bb5b9292-d52b-11e4-8c0e-bd607a021247.jpg) (possible without zombies)
 (door has to be opened though on your side)
![2015-03-28_00024](https://cloud.githubusercontent.com/assets/11538773/6880304/bb62c3e6-d52b-11e4-8d36-32f5f19a479e.jpg)

![2015-03-28_00035](https://cloud.githubusercontent.com/assets/11538773/6880315/bb8be456-d52b-11e4-8306-63f7b2fa37d3.jpg) 
![2015-03-28_00036](https://cloud.githubusercontent.com/assets/11538773/6880316/bb8c1aa2-d52b-11e4-88c8-8fc86c5a7f45.jpg) 
![2015-03-28_00037](https://cloud.githubusercontent.com/assets/11538773/6880317/bb9e742c-d52b-11e4-8e06-6da8570cd8b3.jpg) 
![2015-03-28_00038](https://cloud.githubusercontent.com/assets/11538773/6880318/bb9f921c-d52b-11e4-910d-8d113a4edc78.jpg) 
![2015-03-28_00039](https://cloud.githubusercontent.com/assets/11538773/6880319/bb9fa9dc-d52b-11e4-9165-bf9a6a54f66b.jpg) 
![2015-03-28_00040](https://cloud.githubusercontent.com/assets/11538773/6880321/bba09fcc-d52b-11e4-8440-cd6f8591c0a8.jpg) 
![2015-03-28_00043](https://cloud.githubusercontent.com/assets/11538773/6880323/bbb534d2-d52b-11e4-8878-20ced5419a94.jpg) (you can do this without zombies)
![2015-03-28_00049](https://cloud.githubusercontent.com/assets/11538773/6880329/bbc9c046-d52b-11e4-92d9-fa1b68c144d0.jpg) (zombies get to manage also stuck at the stairs at the right in the corner when you are standing on the edges of it)
![2015-03-28_00052](https://cloud.githubusercontent.com/assets/11538773/6880332/bbcf4a8e-d52b-11e4-96da-bbc3a5862b03.jpg) (sometimes they spawn up the car)
![2015-03-28_00053](https://cloud.githubusercontent.com/assets/11538773/6880334/bbcf80b2-d52b-11e4-99cd-f91cb192eefe.jpg) (it's hard though)
![2015-03-28_00054](https://cloud.githubusercontent.com/assets/11538773/6880333/bbcf6b9a-d52b-11e4-9340-22f6a98c1113.jpg)
![2015-03-28_00058](https://cloud.githubusercontent.com/assets/11538773/6880337/bbe62772-d52b-11e4-9d0b-33ad591d397a.jpg) (you can get up it without a zombie)
![2015-03-28_00060](https://cloud.githubusercontent.com/assets/11538773/6880338/bbe65fd0-d52b-11e4-80f6-033540205ed3.jpg) 
![2015-03-28_00062](https://cloud.githubusercontent.com/assets/11538773/6880401/25d31b46-d530-11e4-904e-d4ade21bcb36.jpg) 
![2015-03-28_00063](https://cloud.githubusercontent.com/assets/11538773/6880405/25d536ce-d530-11e4-807b-eabb4eb62386.jpg) 
![2015-03-28_00065](https://cloud.githubusercontent.com/assets/11538773/6880403/25d4958e-d530-11e4-9b84-513d97e3d8ca.jpg) (urinal again)
![2015-03-28_00025](https://cloud.githubusercontent.com/assets/11538773/6880305/bb6ff16a-d52b-11e4-9b1b-23ad12ee3de2.jpg) 
![2015-03-28_00066](https://cloud.githubusercontent.com/assets/11538773/6880402/25d40a92-d530-11e4-9a0a-219605506047.jpg) 
Zombie Boosting Bugs:
![2015-03-28_00032](https://cloud.githubusercontent.com/assets/11538773/6880311/bb873cee-d52b-11e4-855e-935abe3a6627.jpg) 
![2015-03-28_00074](https://cloud.githubusercontent.com/assets/11538773/6880414/2600b0c4-d530-11e4-84e3-ef8e2571d59a.jpg) You can go up the cart if you jump on a zombie and then upside the cart
![2015-03-28_00031](https://cloud.githubusercontent.com/assets/11538773/6880312/bb877b50-d52b-11e4-84a2-8576d9b38fde.jpg) 
![2015-03-28_00041](https://cloud.githubusercontent.com/assets/11538773/6880320/bb9fd222-d52b-11e4-9b35-6e5f420d7dfe.jpg) 
![2015-03-28_00042](https://cloud.githubusercontent.com/assets/11538773/6880322/bba10994-d52b-11e4-9596-91bc4090d975.jpg)
![2015-03-28_00048](https://cloud.githubusercontent.com/assets/11538773/6880328/bbb7fe7e-d52b-11e4-8da5-ec74f2fd617e.jpg)
![2015-03-28_00057](https://cloud.githubusercontent.com/assets/11538773/6880340/bbeaf446-d52b-11e4-9c11-85493b91dcd6.jpg)
![2015-03-28_00059](https://cloud.githubusercontent.com/assets/11538773/6880339/bbe73bb2-d52b-11e4-84c6-ebaccede7436.jpg)
![2015-03-28_00064](https://cloud.githubusercontent.com/assets/11538773/6880404/25d4ec32-d530-11e4-8db2-8b7cc64a8a9e.jpg)
![2015-03-28_00068](https://cloud.githubusercontent.com/assets/11538773/6880407/25e9a76c-d530-11e4-9940-43bad6b30cd4.jpg) You can throw the hook over the fence and on the other side it's also a Boost bug

Location Bugs:
![2015-03-28_00007](https://cloud.githubusercontent.com/assets/11538773/6880289/bb2c86f0-d52b-11e4-851e-9c68b5559338.jpg) 
![2015-03-28_00011](https://cloud.githubusercontent.com/assets/11538773/6880292/bb3741da-d52b-11e4-998c-430ff661b464.jpg)

**Comment by Fersigal** [comment]
Very much WIP

**Comment by AtheistNMRiH** [comment]
Bug with hook 
![nmo_brooklyn0000](https://cloud.githubusercontent.com/assets/11333747/6880444/bad9c3ec-d563-11e4-97de-a747c37622dd.jpg)
U cant take
And this
![nmo_brooklyn0001](https://cloud.githubusercontent.com/assets/11333747/6880447/e4a204be-d563-11e4-9e55-5f54e179c5b8.jpg)
![nmo_brooklyn0002](https://cloud.githubusercontent.com/assets/11333747/6880449/ef5ad9c6-d563-11e4-95d5-bf5455bf5fd8.jpg)
![nmo_brooklyn0003](https://cloud.githubusercontent.com/assets/11333747/6880450/f4c0da82-d563-11e4-877c-d0502037b201.jpg)

**Comment by Fersigal** [comment]
Next ones i'm publishing are Chinatown and Cabin
