### ISSUE TITLE
Nmo_chinatown map Bugs  (WIP) (needs to be organized in the correct sequence)

### ISSUE THREAD

**Issue by Fersigal** [ZPSNMRiHIssues/nmrihissues#709]
![2015-03-28_00004](https://cloud.githubusercontent.com/assets/11538773/6881468/dacfb0a0-d561-11e4-9097-68591a9689a8.jpg) ZBB
![2015-03-28_00005](https://cloud.githubusercontent.com/assets/11538773/6881469/dacfe8fe-d561-11e4-93b0-8ddbf0ee4c77.jpg) ZBB
![2015-03-28_00006](https://cloud.githubusercontent.com/assets/11538773/6881472/dad29b94-d561-11e4-9cc9-52412d9b9ad7.jpg) OB You can get your items stuck there (doesn't work with can)
![2015-03-28_00007](https://cloud.githubusercontent.com/assets/11538773/6881473/dad367cc-d561-11e4-9cc8-908c119ae782.jpg) IB
![2015-03-28_00008](https://cloud.githubusercontent.com/assets/11538773/6881470/dad0942a-d561-11e4-9431-43700f219b26.jpg) You get stuck when you stand there and zombies won't be able to hit you
![2015-03-28_00009](https://cloud.githubusercontent.com/assets/11538773/6881471/dad2838e-d561-11e4-8ac6-4f720f897e14.jpg) ZBB
![2015-03-28_00010](https://cloud.githubusercontent.com/assets/11538773/6881475/dae7b18c-d561-11e4-8f46-9b040c6487d9.jpg) IB
![2015-03-28_00011](https://cloud.githubusercontent.com/assets/11538773/6881474/dae52fd4-d561-11e4-85b2-1cace15d672e.jpg) ZBBa 1st image
![2015-03-28_00012](https://cloud.githubusercontent.com/assets/11538773/6881476/dae89f52-d561-11e4-96b5-59f921988cee.jpg) ZBBa 2nd image
![2015-03-28_00013](https://cloud.githubusercontent.com/assets/11538773/6881479/daeb3988-d561-11e4-80c6-588e03b1278d.jpg) IB
![2015-03-28_00014](https://cloud.githubusercontent.com/assets/11538773/6881477/daeabe7c-d561-11e4-822d-779c1648956e.jpg) ZBB
![2015-03-28_00015](https://cloud.githubusercontent.com/assets/11538773/6881478/daeaf568-d561-11e4-97c3-b2dbafae1b18.jpg) ZBB
![2015-03-28_00016](https://cloud.githubusercontent.com/assets/11538773/6881480/dafd0244-d561-11e4-9aff-36bc2c6a78bb.jpg) IB
![2015-03-28_00017](https://cloud.githubusercontent.com/assets/11538773/6881481/dafeafae-d561-11e4-8c6e-61e13c942700.jpg) IB
![2015-03-28_00018](https://cloud.githubusercontent.com/assets/11538773/6881482/db00890a-d561-11e4-82ec-fed94b699b8f.jpg) IB (if the can is in front)
![2015-03-28_00019](https://cloud.githubusercontent.com/assets/11538773/6881483/db02163a-d561-11e4-9ffc-4c735f737e5f.jpg) IB
![2015-03-28_00020](https://cloud.githubusercontent.com/assets/11538773/6881484/db03ff04-d561-11e4-9088-7e3aaf29b116.jpg) ZBB (at the ladder objective, might look a bit confusing)
![2015-03-28_00021](https://cloud.githubusercontent.com/assets/11538773/6881485/db043320-d561-11e4-9eff-17a9b8c8598a.jpg) ZBBb 1st image (at the metal gate)
![2015-03-28_00022](https://cloud.githubusercontent.com/assets/11538773/6881487/db14d446-d561-11e4-9ac5-4406eaccc90a.jpg) ZBBb 2nd image 
![2015-03-28_00023](https://cloud.githubusercontent.com/assets/11538773/6881486/db14a444-d561-11e4-9d54-65a6a3f3b7e2.jpg) IB
![2015-03-28_00024](https://cloud.githubusercontent.com/assets/11538773/6881488/db156366-d561-11e4-96af-6324f73d0493.jpg) ZBB (after the launderette there's a metal fence)
![2015-03-28_00025](https://cloud.githubusercontent.com/assets/11538773/6881489/db19557a-d561-11e4-9692-4e8453f812db.jpg) ZBB
![2015-03-28_00026](https://cloud.githubusercontent.com/assets/11538773/6881490/db1ac928-d561-11e4-8582-b5bfa0486df9.jpg) IB
![2015-03-28_00027](https://cloud.githubusercontent.com/assets/11538773/6881491/db1c58ec-d561-11e4-93d5-916f76a1bae7.jpg) OB (zombies get stuck after you lured them onto the trash can)
![2015-03-28_00028](https://cloud.githubusercontent.com/assets/11538773/6881493/db2db4ca-d561-11e4-9769-95340fc9fe70.jpg) Weird bug (after the zombie below died he went on the floor)
![2015-03-28_00029](https://cloud.githubusercontent.com/assets/11538773/6881494/db2e9bba-d561-11e4-8b2d-351f7d362b35.jpg) IB 
![2015-03-28_00030](https://cloud.githubusercontent.com/assets/11538773/6881492/db2c324e-d561-11e4-98a9-fc883a88af78.jpg) IB if standing correctly in the middle (sewers end)
![2015-03-28_00031](https://cloud.githubusercontent.com/assets/11538773/6881495/db3289f0-d561-11e4-8d06-f7fe65afb00e.jpg) ZBB (Tought's publication)
![2015-03-28_00032](https://cloud.githubusercontent.com/assets/11538773/6881496/db333b3e-d561-11e4-8139-dd6d618b2973.jpg) Collison bug
![2015-03-28_00033](https://cloud.githubusercontent.com/assets/11538773/6881497/db3464f0-d561-11e4-90ad-1df97d57b828.jpg) ZBB
![2015-03-28_00034](https://cloud.githubusercontent.com/assets/11538773/6881498/db429be2-d561-11e4-95e1-a32a0b16f17f.jpg) OB you can get up the fire truck without the help of zombies by jump crouching and sprinting (tricky)
![2015-03-28_00035](https://cloud.githubusercontent.com/assets/11538773/6881587/a0ce9df4-d565-11e4-85d7-9eb274b7fd51.jpg) ZBB
![2015-03-28_00036](https://cloud.githubusercontent.com/assets/11538773/6881591/a0d1cdbc-d565-11e4-946a-bf3e3f7afbf2.jpg) ZBB
![2015-03-28_00037](https://cloud.githubusercontent.com/assets/11538773/6881590/a0d04320-d565-11e4-8813-b31cac1da92b.jpg) ZBB
![2015-03-28_00038](https://cloud.githubusercontent.com/assets/11538773/6881588/a0ceefe8-d565-11e4-93ec-e69b4abba1d0.jpg) ZBB
![2015-03-28_00039](https://cloud.githubusercontent.com/assets/11538773/6881589/a0cfa082-d565-11e4-89be-de5efb3d9548.jpg) ZBB
![2015-03-28_00040](https://cloud.githubusercontent.com/assets/11538773/6881592/a0d24b48-d565-11e4-81e2-de728280f3f1.jpg) IB 
![2015-03-28_00041](https://cloud.githubusercontent.com/assets/11538773/6881593/a0e458d8-d565-11e4-990c-a0b65d2e6f8f.jpg) IB
![2015-03-28_00042](https://cloud.githubusercontent.com/assets/11538773/6881594/a0e5961c-d565-11e4-893c-4cc17015daa2.jpg) ZBB

**Comment by Fersigal** [comment]
If you can't find the place please tell me then i'll try to describe it

**Comment by Smil3yRiley** [comment]
Some of these should be fixed in r8294 on the map end, will have to update the nav mesh to fix some of these AI issues
