### ISSUE TITLE
Nmo_fema map bugs

### ISSUE THREAD

**Issue by Fersigal** [ZPSNMRiHIssues/nmrihissues#715]
CTRL + F: and search for JUS, ZBB, TB, OB
Jump up Spots, Zombie Boosting Bugs, Texture Bugs, Other Bugs 
PS: Lou you were right, almost 90 Jump up bugs 
![2015-03-29_00104](https://cloud.githubusercontent.com/assets/11538773/6885809/842fc684-d62b-11e4-931b-5dd944bc6d0c.jpg) no bug, just for fun (nmrih written with smashes)
![2015-03-29_00105](https://cloud.githubusercontent.com/assets/11538773/6885810/843073f4-d62b-11e4-8d53-d98731b4a6ea.jpg) jump up spot (JUS)
![2015-03-29_00106](https://cloud.githubusercontent.com/assets/11538773/6885812/84342a44-d62b-11e4-86ab-1b4da439dca6.jpg) JUS
![2015-03-29_00107](https://cloud.githubusercontent.com/assets/11538773/6885813/8434d804-d62b-11e4-9992-8b097de97c49.jpg) TB (the lower part of the helms are untextured)
![2015-03-29_00108](https://cloud.githubusercontent.com/assets/11538773/6885814/84359ec4-d62b-11e4-9860-1ea25fc6ca29.jpg) ZBB
![2015-03-29_00109](https://cloud.githubusercontent.com/assets/11538773/6885811/8433656e-d62b-11e4-890f-e3870fa9cd1d.jpg) JUS
![2015-03-29_00110](https://cloud.githubusercontent.com/assets/11538773/6885816/8446ea76-d62b-11e4-91b3-05c3652c74ef.jpg) JUS
![2015-03-29_00111](https://cloud.githubusercontent.com/assets/11538773/6885815/8446cdac-d62b-11e4-9be4-c14ac7c7dc8b.jpg) JUS
![2015-03-29_00112](https://cloud.githubusercontent.com/assets/11538773/6885820/844a3bb8-d62b-11e4-996a-597682a12ae9.jpg) JUS
![2015-03-29_00113](https://cloud.githubusercontent.com/assets/11538773/6885817/8448a320-d62b-11e4-9948-98cc5d09db7b.jpg) ZBB
![2015-03-29_00114](https://cloud.githubusercontent.com/assets/11538773/6885819/844a3d98-d62b-11e4-9fdb-7f1a53c262e2.jpg) ZBB
![2015-03-29_00115](https://cloud.githubusercontent.com/assets/11538773/6885818/844a3b5e-d62b-11e4-9713-c5b5e35772f1.jpg) JUS
![2015-03-29_00116](https://cloud.githubusercontent.com/assets/11538773/6885821/845e6228-d62b-11e4-9d38-ce40bf1f9aa6.jpg) JUS
![2015-03-29_00117](https://cloud.githubusercontent.com/assets/11538773/6885822/845e86cc-d62b-11e4-8484-b73d3b591269.jpg) JUS (no zombies are required only pure skill)
![2015-03-29_00118](https://cloud.githubusercontent.com/assets/11538773/6885823/8460e6ec-d62b-11e4-8628-7662d0fda64b.jpg) JUS
![2015-03-29_00119](https://cloud.githubusercontent.com/assets/11538773/6885824/84619254-d62b-11e4-8ed1-c14f44ac7e9e.jpg) ZBB
![2015-03-29_00120](https://cloud.githubusercontent.com/assets/11538773/6885825/846315ca-d62b-11e4-9810-3fccde3d8945.jpg) JUS
![2015-03-29_00121](https://cloud.githubusercontent.com/assets/11538773/6885826/846379de-d62b-11e4-9ddd-af79bcbf00c2.jpg) JUS
![2015-03-29_00122](https://cloud.githubusercontent.com/assets/11538773/6885827/8473983c-d62b-11e4-98a9-13586142ea63.jpg) JUS (no zombies required only pure skill)
![2015-03-29_00123](https://cloud.githubusercontent.com/assets/11538773/6885828/84777830-d62b-11e4-9540-4d6e83160446.jpg) OB (pills are stuck in the ground)
![2015-03-29_00124](https://cloud.githubusercontent.com/assets/11538773/6885829/84783c2a-d62b-11e4-98eb-3517f5937df9.jpg) ZBB
![2015-03-29_00125](https://cloud.githubusercontent.com/assets/11538773/6885830/8478544e-d62b-11e4-8803-f358f5ff7edb.jpg) JUS
![2015-03-29_00126](https://cloud.githubusercontent.com/assets/11538773/6885832/847abd56-d62b-11e4-9593-a6a3248e75bb.jpg) JUS
![2015-03-29_00127](https://cloud.githubusercontent.com/assets/11538773/6885831/847a0212-d62b-11e4-9f19-80b5f790f793.jpg) JUS
![2015-03-29_00128](https://cloud.githubusercontent.com/assets/11538773/6885833/8489c1d4-d62b-11e4-89a5-2c03013ab253.jpg) JUS
![2015-03-29_00129](https://cloud.githubusercontent.com/assets/11538773/6885836/84904f22-d62b-11e4-8dce-b1d3dad2ba81.jpg) JUS
![2015-03-29_00130](https://cloud.githubusercontent.com/assets/11538773/6885837/849126d6-d62b-11e4-93d0-7a689ec6ba28.jpg) OB (there's a ladder mechanism at the metal fence)
![2015-03-29_00131](https://cloud.githubusercontent.com/assets/11538773/6885835/848ff5fe-d62b-11e4-9d79-be221a6420dc.jpg) OB  (ladder mechanism, same room but other side)
![2015-03-29_00132](https://cloud.githubusercontent.com/assets/11538773/6885834/848f95a0-d62b-11e4-84fd-b0f0bc30728d.jpg) JUS
![2015-03-29_00133](https://cloud.githubusercontent.com/assets/11538773/6885838/8493f4d8-d62b-11e4-93d2-c212aae17b42.jpg) JUS
![2015-03-29_00134](https://cloud.githubusercontent.com/assets/11538773/6885839/84a31080-d62b-11e4-8a8d-fc59ee137f7c.jpg) JUS
![2015-03-29_00135](https://cloud.githubusercontent.com/assets/11538773/6885840/84a77ecc-d62b-11e4-9c82-20f1c0738af9.jpg) JUS
![2015-03-29_00136](https://cloud.githubusercontent.com/assets/11538773/6885842/84a99f04-d62b-11e4-86b6-fad5608170a5.jpg) JUS
![2015-03-29_00137](https://cloud.githubusercontent.com/assets/11538773/6885843/84aa3ce8-d62b-11e4-8649-d9e07ac052ab.jpg) JUS
![2015-03-29_00138](https://cloud.githubusercontent.com/assets/11538773/6885841/84a8705c-d62b-11e4-97a5-7859ecb46431.jpg) JUS
![2015-03-29_00139](https://cloud.githubusercontent.com/assets/11538773/6885844/84ab0a38-d62b-11e4-9e28-4e676ff9932c.jpg) JUS (no zombies required)
![2015-03-29_00140](https://cloud.githubusercontent.com/assets/11538773/6885845/84b8cf9c-d62b-11e4-81d4-ccffc745cab9.jpg) JUS
![2015-03-29_00141](https://cloud.githubusercontent.com/assets/11538773/6885846/84c32546-d62b-11e4-8b86-b3c6344dd14e.jpg) JUS (ladder mechanism)
![2015-03-29_00143](https://cloud.githubusercontent.com/assets/11538773/6885848/84c5f140-d62b-11e4-90b5-23fe992a6ae8.jpg) OB (if the opening is broken the player that goes after will always get dmged for some reason)
![2015-03-29_00144](https://cloud.githubusercontent.com/assets/11538773/6885847/84c5c3aa-d62b-11e4-8b98-926de0beff4b.jpg) JUS 
![2015-03-29_00145](https://cloud.githubusercontent.com/assets/11538773/6885850/84c734a6-d62b-11e4-97ab-a0febc2c7b0a.jpg) TB
![2015-03-29_00146](https://cloud.githubusercontent.com/assets/11538773/6885851/84d25bce-d62b-11e4-92a4-5e572ef2c30f.jpg) OB (you get stuck here)
![2015-03-29_00147](https://cloud.githubusercontent.com/assets/11538773/6885852/84d9bfe0-d62b-11e4-839d-2240d5faa867.jpg) JUS (no zombies required only pure skill)
![2015-03-29_00148](https://cloud.githubusercontent.com/assets/11538773/6885854/84dc1f60-d62b-11e4-981f-95dd021f0813.jpg) (objective bug, you can throw any explosive into the thing and it will close)
![2015-03-29_00150](https://cloud.githubusercontent.com/assets/11538773/6885856/84ddd95e-d62b-11e4-8b7b-33d1ae1a7bd6.jpg) JUS
![2015-03-29_00151](https://cloud.githubusercontent.com/assets/11538773/6885853/84dbe360-d62b-11e4-9663-ff0a392c9e55.jpg) JUS
![2015-03-29_00152](https://cloud.githubusercontent.com/assets/11538773/6885857/84e96dc8-d62b-11e4-9469-47e5acb10345.jpg) JUS
![2015-03-29_00153](https://cloud.githubusercontent.com/assets/11538773/6885865/852e4290-d62b-11e4-8afc-fe4295ee3ae9.jpg) OB (zombies won't be able to hit you)
![2015-03-29_00154](https://cloud.githubusercontent.com/assets/11538773/6885863/8521c3bc-d62b-11e4-9795-bfcedcdf8300.jpg) JUS
![2015-03-29_00155](https://cloud.githubusercontent.com/assets/11538773/6885858/85097de8-d62b-11e4-91ee-44e2f48d7720.jpg) JUS
![2015-03-29_00156](https://cloud.githubusercontent.com/assets/11538773/6885859/850abd02-d62b-11e4-8f2b-5968aafca76b.jpg) JUS
![2015-03-29_00157](https://cloud.githubusercontent.com/assets/11538773/6885866/8531b43e-d62b-11e4-8666-aedc33d0f825.jpg) JUS 
![2015-03-29_00158](https://cloud.githubusercontent.com/assets/11538773/6885860/850b34a8-d62b-11e4-9ed6-70326abc9989.jpg) JUS
![2015-03-29_00159](https://cloud.githubusercontent.com/assets/11538773/6885861/851fdd0e-d62b-11e4-8e57-8fb2078f0972.jpg) JUS
![2015-03-29_00160](https://cloud.githubusercontent.com/assets/11538773/6885864/85222e92-d62b-11e4-9367-917812fa7917.jpg) JUS
![2015-03-29_00161](https://cloud.githubusercontent.com/assets/11538773/6885862/8520cb88-d62b-11e4-96ad-f76fa7550a66.jpg) JUS
![2015-03-29_00162](https://cloud.githubusercontent.com/assets/11538773/6885869/8536ff8e-d62b-11e4-8157-13c5d37aae72.jpg) JUS (you can get after the little trailer wagons)
![2015-03-29_00163](https://cloud.githubusercontent.com/assets/11538773/6885867/853602c8-d62b-11e4-89e2-6881aadcca0d.jpg) JUS (you can also get after the boxes at your left when you leave the place that's gonna explode)
![2015-03-29_00164](https://cloud.githubusercontent.com/assets/11538773/6885868/8536b952-d62b-11e4-8d8d-516edc4fe17a.jpg) JUS
![2015-03-29_00165](https://cloud.githubusercontent.com/assets/11538773/6885870/8537842c-d62b-11e4-9f15-5bd3eac8ef3e.jpg) JUS
![2015-03-29_00166](https://cloud.githubusercontent.com/assets/11538773/6885872/855700cc-d62b-11e4-9d23-abc0ca58ac3f.jpg) TB
![2015-03-29_00167](https://cloud.githubusercontent.com/assets/11538773/6885871/8556befa-d62b-11e4-8f03-5a48c4d34c20.jpg) JUS
![2015-03-29_00168](https://cloud.githubusercontent.com/assets/11538773/6885874/85588438-d62b-11e4-9f31-a9f4a3aabe27.jpg) OB (objective tempt to break if you go at the metal fence in the water, objective pathing is fucked)
![2015-03-29_00169](https://cloud.githubusercontent.com/assets/11538773/6885875/8559390a-d62b-11e4-9ce9-bd36e247c72b.jpg) JUS
![2015-03-29_00170](https://cloud.githubusercontent.com/assets/11538773/6885876/85597802-d62b-11e4-8497-6869d130e93e.jpg) OB (you get stuck if you get after crate)
![2015-03-29_00171](https://cloud.githubusercontent.com/assets/11538773/6885873/85577c8c-d62b-11e4-97aa-27754db93ff5.jpg) ZBB
![2015-03-29_00172](https://cloud.githubusercontent.com/assets/11538773/6885878/856e1e60-d62b-11e4-928d-92b355342fd5.jpg) JUS
![2015-03-29_00173](https://cloud.githubusercontent.com/assets/11538773/6885877/856c0f1c-d62b-11e4-8769-4e54b8b8f710.jpg) JUS
![2015-03-29_00174](https://cloud.githubusercontent.com/assets/11538773/6885879/856f2436-d62b-11e4-9b0d-765f99467fb3.jpg) JUS
![2015-03-29_00175](https://cloud.githubusercontent.com/assets/11538773/6885881/85706864-d62b-11e4-980b-b999e69edc56.jpg) JUS
![2015-03-29_00176](https://cloud.githubusercontent.com/assets/11538773/6885880/856f2332-d62b-11e4-97b5-85a4e94d4ccc.jpg) JUS
![2015-03-29_00177](https://cloud.githubusercontent.com/assets/11538773/6885882/85720f70-d62b-11e4-9800-f6fcb83ff0c3.jpg) ZBB
![2015-03-29_00178](https://cloud.githubusercontent.com/assets/11538773/6885883/858db5b8-d62b-11e4-9fbe-8a4e9445799c.jpg) ZBB
![2015-03-29_00179](https://cloud.githubusercontent.com/assets/11538773/6885887/8591f006-d62b-11e4-9c2d-81199b963b41.jpg) ZBB
![2015-03-29_00180](https://cloud.githubusercontent.com/assets/11538773/6885884/858ef130-d62b-11e4-88c1-a4755d53f658.jpg) ZBB
![2015-03-29_00181](https://cloud.githubusercontent.com/assets/11538773/6885888/8593249e-d62b-11e4-8528-6bbbb2b88cf7.jpg) JUS (you can still get on it however zombies won't be able to hit you if you aim correctly at the middle)
![2015-03-29_00182](https://cloud.githubusercontent.com/assets/11538773/6885886/859018e4-d62b-11e4-9a6a-c5712f0a7166.jpg) JUS
![2015-03-29_00183](https://cloud.githubusercontent.com/assets/11538773/6885885/858ff17a-d62b-11e4-974c-5c2c2a1a05b0.jpg) JUS
![2015-03-29_00184](https://cloud.githubusercontent.com/assets/11538773/6885889/85a4ab42-d62b-11e4-9e6b-a8ac78a9ff83.jpg) JUS
![2015-03-29_00185](https://cloud.githubusercontent.com/assets/11538773/6885890/85a61c7a-d62b-11e4-8023-96823994e487.jpg) JUS (no zombies required location is shown)
![2015-03-29_00186](https://cloud.githubusercontent.com/assets/11538773/6885891/85a68930-d62b-11e4-819a-db152ca54d0f.jpg) JUS
![2015-03-29_00187](https://cloud.githubusercontent.com/assets/11538773/6885892/85a729f8-d62b-11e4-80f8-38ffa4ffcff9.jpg) JUS
![2015-03-29_00188](https://cloud.githubusercontent.com/assets/11538773/6885893/85a8f2c4-d62b-11e4-85af-db617dc7f766.jpg) JUS
![2015-03-29_00189](https://cloud.githubusercontent.com/assets/11538773/6885894/85a92ffa-d62b-11e4-8dec-d11bba91c4b9.jpg) OB (you get stuck)
![2015-03-29_00190](https://cloud.githubusercontent.com/assets/11538773/6885897/85bc6ca0-d62b-11e4-8b65-8d259dd459d0.jpg) JUS
![2015-03-29_00191](https://cloud.githubusercontent.com/assets/11538773/6885895/85ba7134-d62b-11e4-9816-56dea4fd0b61.jpg) JUS
![2015-03-29_00192](https://cloud.githubusercontent.com/assets/11538773/6885896/85bb563a-d62b-11e4-947a-f2115ad42b93.jpg) OB (zombies tend to block the passage, maybe make an extra addition to it so you'll have to go up a ladder after it and go down again ?)
![2015-03-29_00193](https://cloud.githubusercontent.com/assets/11538773/6885898/85be3f30-d62b-11e4-9185-19982ededa84.jpg) TB
![2015-03-29_00194](https://cloud.githubusercontent.com/assets/11538773/6885900/85c03f06-d62b-11e4-9252-10dcb32261df.jpg) JUS
![2015-03-29_00195](https://cloud.githubusercontent.com/assets/11538773/6885899/85c016e8-d62b-11e4-81dc-24f23f34ced4.jpg) JUS
![2015-03-29_00196](https://cloud.githubusercontent.com/assets/11538773/6885901/85d309ec-d62b-11e4-89f2-ceb71c92738b.jpg) TB
![2015-03-29_00197](https://cloud.githubusercontent.com/assets/11538773/6885904/85d5676e-d62b-11e4-8f37-88728fb48516.jpg) JUS
![2015-03-29_00198](https://cloud.githubusercontent.com/assets/11538773/6885903/85d531cc-d62b-11e4-9cb4-0157b8ad92b4.jpg) JUS
![2015-03-29_00199](https://cloud.githubusercontent.com/assets/11538773/6885905/85d5dd02-d62b-11e4-94de-fb8bf94db805.jpg) JUS
![2015-03-29_00200](https://cloud.githubusercontent.com/assets/11538773/6885906/85d624b0-d62b-11e4-95ab-2a5173eba41e.jpg) JUS
![2015-03-29_00201](https://cloud.githubusercontent.com/assets/11538773/6885902/85d4a856-d62b-11e4-9a4d-37b26a86dbae.jpg) JUS
![2015-03-29_00202](https://cloud.githubusercontent.com/assets/11538773/6885907/85e878f4-d62b-11e4-91ed-bdabf0844898.jpg) OB (there's a gap between the rock which you can use to avoid doing the tnt objective and so you can skip it easily)
![2015-03-29_00203](https://cloud.githubusercontent.com/assets/11538773/6885910/85ec66d0-d62b-11e4-8de8-26f9aed09dc7.jpg) OB Right side shown of previous image
![2015-03-29_00204](https://cloud.githubusercontent.com/assets/11538773/6885911/85ed2408-d62b-11e4-8245-b80b01dbed51.jpg) OB (at the rock you can explode you can also go true it at the left side)
![2015-03-29_00205](https://cloud.githubusercontent.com/assets/11538773/6885912/85ed4eba-d62b-11e4-8b0c-580c1fdb4653.jpg) JUS
![2015-03-29_00206](https://cloud.githubusercontent.com/assets/11538773/6885908/85ea97ec-d62b-11e4-845b-70aad47c1d6e.jpg) JUS
![2015-03-29_00207](https://cloud.githubusercontent.com/assets/11538773/6885909/85eb3bde-d62b-11e4-9d82-885920af97dd.jpg) JUS
![2015-03-29_00208](https://cloud.githubusercontent.com/assets/11538773/6885914/8608f19c-d62b-11e4-9cf4-a5e141c028e9.jpg) JUS
![2015-03-29_00209](https://cloud.githubusercontent.com/assets/11538773/6885916/8609e836-d62b-11e4-9a84-693be61fd2a9.jpg) JUS
![2015-03-29_00210](https://cloud.githubusercontent.com/assets/11538773/6885913/86087ae6-d62b-11e4-8375-a2b4074a5d78.jpg) ZBB
![2015-03-29_00211](https://cloud.githubusercontent.com/assets/11538773/6885915/86091456-d62b-11e4-9b65-5da51f5d3e20.jpg) JUS
![2015-03-29_00212](https://cloud.githubusercontent.com/assets/11538773/6885917/860a83fe-d62b-11e4-9136-14ed96a4fc08.jpg) JUS
![2015-03-29_00213](https://cloud.githubusercontent.com/assets/11538773/6885918/860c70a6-d62b-11e4-8c3c-251ec56dd935.jpg) JUS (check LATISARG his videos for more concrete detailed showing the exact pathing of where you can get to it, [link: https://www.youtube.com/watch?v=z22STFXxvgI] mainly check the end at 8 minutes)
![2015-03-29_00214](https://cloud.githubusercontent.com/assets/11538773/6885923/86213ae0-d62b-11e4-864d-c1b8e24c7564.jpg) JUS
![2015-03-29_00215](https://cloud.githubusercontent.com/assets/11538773/6885919/861f0144-d62b-11e4-964d-0fc6dd1278b8.jpg) JUS 
![2015-03-29_00216](https://cloud.githubusercontent.com/assets/11538773/6885924/86219260-d62b-11e4-9975-4db1c87b93a2.jpg) JUS
![2015-03-29_00217](https://cloud.githubusercontent.com/assets/11538773/6885920/861f318c-d62b-11e4-8e77-2eebc1a1c3b6.jpg) JUS
![2015-03-29_00218](https://cloud.githubusercontent.com/assets/11538773/6885922/86213e0a-d62b-11e4-80e1-149aa44e2d3a.jpg) ZBB
![2015-03-29_00219](https://cloud.githubusercontent.com/assets/11538773/6885921/86211e20-d62b-11e4-9bb3-8fc272e3131d.jpg) JUS 
![2015-03-29_00220](https://cloud.githubusercontent.com/assets/11538773/6885925/8644b024-d62b-11e4-9168-2c9e23735c67.jpg) JUS
![2015-03-29_00221](https://cloud.githubusercontent.com/assets/11538773/6885926/8644d798-d62b-11e4-905c-efd8ee1a83ab.jpg) JUS
![2015-03-29_00223](https://cloud.githubusercontent.com/assets/11538773/6885929/8649c5be-d62b-11e4-9d13-5fbc91478309.jpg) TB
![2015-03-29_00224](https://cloud.githubusercontent.com/assets/11538773/6885930/864a7ebe-d62b-11e4-924c-1b79fcfcdd97.jpg) OB (left side of the ladder is no ladder and you fall off completely)
![2015-03-29_00225](https://cloud.githubusercontent.com/assets/11538773/6885928/86495dae-d62b-11e4-939d-a7727c6ccd9f.jpg) (end result, don't note the not welded objective)

**Comment by AtheistNMRiH** [comment]
too many, biaatch

**Comment by lousaffire** [comment]
Just mainly jump up spots then really, biaaatch.

**Comment by Fersigal** [comment]
Hey ): don't be salty about it

**Comment by AtheistNMRiH** [comment]
Also there are 2 place, where u can get stuck
![nmo_fema0013](https://cloud.githubusercontent.com/assets/11333747/6918739/2ce4373c-d7db-11e4-9896-63f46c455490.jpg)
![nmo_fema0018](https://cloud.githubusercontent.com/assets/11333747/6918748/3b1076ea-d7db-11e4-91db-b5369b7e12f7.jpg)

**Comment by lousaffire** [comment]
okok i may have a little sand in my vagina,  but could you please at least separate the jump ups from actual bugs, creating a massive list of jpegs is not as helpful as you might think...

**Comment by Fersigal** [comment]
I'm planning on doing that, that's why it's saying WIP , the Jump up bugs will be classified as Invulnerable bugs or other bugs if they have a massive next step parts like the jumpable invisible walls at the last part.

**Comment by lousaffire** [comment]
Thanks fersigal, these should all be fixed before end of weekend.
