### ISSUE TITLE
Nmo_zephyr map bugs

### ISSUE THREAD

**Issue by Fersigal** [ZPSNMRiHIssues/nmrihissues#717]
Invulnerable Bugs:
![2015-03-29_00273](https://cloud.githubusercontent.com/assets/11538773/6886478/9e4a4480-d640-11e4-9cf9-21edb8e9b1e3.jpg)
![2015-03-29_00274](https://cloud.githubusercontent.com/assets/11538773/6886477/9e498e3c-d640-11e4-979a-1abc45862829.jpg) 
![2015-03-29_00275](https://cloud.githubusercontent.com/assets/11538773/6886479/9e4a68ca-d640-11e4-966a-c59578adead5.jpg) 
![2015-03-29_00276](https://cloud.githubusercontent.com/assets/11538773/6886480/9e58cc76-d640-11e4-9b20-a2012cfb1086.jpg) 
![2015-03-29_00279](https://cloud.githubusercontent.com/assets/11538773/6886484/9e612470-d640-11e4-8563-ab1e400ce13b.jpg)
![2015-03-29_00281](https://cloud.githubusercontent.com/assets/11538773/6886483/9e5fdda4-d640-11e4-82b2-0ad0a0b73f00.jpg)
![2015-03-29_00283](https://cloud.githubusercontent.com/assets/11538773/6886487/9e736202-d640-11e4-98e1-0a75315e0d26.jpg)
![2015-03-29_00285](https://cloud.githubusercontent.com/assets/11538773/6886489/9e77ceaa-d640-11e4-9905-425d885508cd.jpg)
![2015-03-29_00290](https://cloud.githubusercontent.com/assets/11538773/6886493/9e89dcbc-d640-11e4-8882-9623024a356a.jpg) (although crawlers can still get u)
![2015-03-29_00291](https://cloud.githubusercontent.com/assets/11538773/6886494/9e8d0752-d640-11e4-9b34-118ef7e8e0bf.jpg)
![2015-03-29_00292](https://cloud.githubusercontent.com/assets/11538773/6886496/9e8f4210-d640-11e4-826e-a1619c038fa5.jpg)
![2015-03-29_00296](https://cloud.githubusercontent.com/assets/11538773/6886499/9ea0c8e6-d640-11e4-8866-543a5bf94035.jpg) (you can keep the door open and zombies won't be able to hit you)
![2015-03-29_00297](https://cloud.githubusercontent.com/assets/11538773/6886500/9ea3e328-d640-11e4-8edd-c3d86a20eeae.jpg)
![2015-03-29_00302](https://cloud.githubusercontent.com/assets/11538773/6886505/9eb7d46e-d640-11e4-8529-14fc48ab264a.jpg)
![2015-03-29_00312](https://cloud.githubusercontent.com/assets/11538773/6886515/9ed4538c-d640-11e4-8b1a-6818b25d704d.jpg)
![2015-03-29_00313](https://cloud.githubusercontent.com/assets/11538773/6886516/9edaa368-d640-11e4-88a5-0b830cc57fe9.jpg)
![2015-03-29_00316](https://cloud.githubusercontent.com/assets/11538773/6886520/9eea1f1e-d640-11e4-9c13-b6e2fb1a0d8a.jpg)
![2015-03-29_00320](https://cloud.githubusercontent.com/assets/11538773/6886523/9ef9ec00-d640-11e4-9ce1-8c14de0dfdd3.jpg)
![2015-03-29_00321](https://cloud.githubusercontent.com/assets/11538773/6886524/9efd7122-d640-11e4-93ca-751ce3048626.jpg)
![2015-03-29_00322](https://cloud.githubusercontent.com/assets/11538773/6886525/9f003efc-d640-11e4-98b8-42b134222357.jpg)
![2015-03-29_00323](https://cloud.githubusercontent.com/assets/11538773/6886526/9f02faca-d640-11e4-9aab-c50940d3628c.jpg)
![2015-03-29_00324](https://cloud.githubusercontent.com/assets/11538773/6886527/9f0900fa-d640-11e4-9a21-207f3838e6e2.jpg) (no dmg and no infection)
Zombie Boosting Bugs:
![2015-03-29_00278](https://cloud.githubusercontent.com/assets/11538773/6886482/9e5fb95a-d640-11e4-9c02-725d7588120a.jpg)
![2015-03-29_00286](https://cloud.githubusercontent.com/assets/11538773/6886491/9e7929d0-d640-11e4-84aa-d9c3a091422d.jpg)
![2015-03-29_00303](https://cloud.githubusercontent.com/assets/11538773/6886506/9eb95348-d640-11e4-8d7f-7d8e96133ad9.jpg) (at the train station at boxes, get first on the metal door handle)
![2015-03-29_00305](https://cloud.githubusercontent.com/assets/11538773/6886507/9eba9b4a-d640-11e4-8343-2566369a2464.jpg)
![2015-03-29_00307](https://cloud.githubusercontent.com/assets/11538773/6886510/9ec34e0c-d640-11e4-83b4-fab98a81c21b.jpg)
![2015-03-29_00315](https://cloud.githubusercontent.com/assets/11538773/6886518/9ee6bfe0-d640-11e4-8617-c33b83ca62d6.jpg)
![2015-03-29_00317](https://cloud.githubusercontent.com/assets/11538773/6886519/9ee95e58-d640-11e4-9add-2cefcde1df5f.jpg)
![2015-03-29_00318](https://cloud.githubusercontent.com/assets/11538773/6886521/9eeb9d76-d640-11e4-93d2-aec881c64345.jpg)
Texture Bugs:
![2015-03-29_00277](https://cloud.githubusercontent.com/assets/11538773/6886481/9e5ea89e-d640-11e4-9aa3-07babe74f768.jpg)
![2015-03-29_00298](https://cloud.githubusercontent.com/assets/11538773/6886501/9ea43742-d640-11e4-9bb9-abf3b098e998.jpg) (see left top corner)
![2015-03-29_00311](https://cloud.githubusercontent.com/assets/11538773/6886514/9ed3d100-d640-11e4-8089-43e6ca4f56a5.jpg) (the train rails go over them and sometimes it kinda looks confusing when you see it)
Location Bugs:
![2015-03-29_00314](https://cloud.githubusercontent.com/assets/11538773/6886517/9ee3a2b0-d640-11e4-91ee-7083cf13af38.jpg)
![2015-03-29_00288](https://cloud.githubusercontent.com/assets/11538773/6886492/9e843f64-d640-11e4-97be-3dbc2110c5df.jpg)
Other Bugs:
![2015-03-29_00271](https://cloud.githubusercontent.com/assets/11538773/6886476/9e4945b2-d640-11e4-94ea-e6e969cf6a49.jpg) OB
![2015-03-29_00272](https://cloud.githubusercontent.com/assets/11538773/6886475/9e487b8c-d640-11e4-81cb-6ae1ca9406f8.jpg) Arrow piercing bug (sound)
![2015-03-29_00280](https://cloud.githubusercontent.com/assets/11538773/6886485/9e62058e-d640-11e4-8d38-0f05a166ab78.jpg) OB
![2015-03-29_00282](https://cloud.githubusercontent.com/assets/11538773/6886486/9e6d6dca-d640-11e4-9d1f-f1a6d92d85e5.jpg) OB
![2015-03-29_00284](https://cloud.githubusercontent.com/assets/11538773/6886488/9e77188e-d640-11e4-8383-586b371e22a5.jpg) OB
![2015-03-29_00293](https://cloud.githubusercontent.com/assets/11538773/6886497/9e8ff8e0-d640-11e4-80ec-c7b726870f3e.jpg) OB (when you go up the fence opens when ur head reaches the top)
![2015-03-29_00294](https://cloud.githubusercontent.com/assets/11538773/6886495/9e8d85ec-d640-11e4-99ac-3643d3065def.jpg) OBa (you won't get killed if aiming precisely at the sides of it)
![2015-03-29_00295](https://cloud.githubusercontent.com/assets/11538773/6886498/9e99b4f2-d640-11e4-85c7-ce833e983710.jpg)OBa 2nd image
![2015-03-29_00299](https://cloud.githubusercontent.com/assets/11538773/6886503/9ea5fec4-d640-11e4-8778-3c8ea20382e9.jpg) OB
![2015-03-29_00300](https://cloud.githubusercontent.com/assets/11538773/6886502/9ea4d45e-d640-11e4-9c4c-2feda6343a6b.jpg) OB
![2015-03-29_00301](https://cloud.githubusercontent.com/assets/11538773/6886504/9eae5f38-d640-11e4-98ee-1eb07163f83b.jpg) OB
![2015-03-29_00304](https://cloud.githubusercontent.com/assets/11538773/6886508/9ebaeba4-d640-11e4-8f30-2628f204556a.jpg) OB (you can hang onto the ladder when the train departs)
![2015-03-29_00308](https://cloud.githubusercontent.com/assets/11538773/6886511/9ecc3850-d640-11e4-893f-66e7cace6ced.jpg) OBb
![2015-03-29_00309](https://cloud.githubusercontent.com/assets/11538773/6886512/9ed02744-d640-11e4-9900-309d411d0c08.jpg) OBb 2nd image
![2015-03-29_00310](https://cloud.githubusercontent.com/assets/11538773/6886513/9ed29ac4-d640-11e4-89a0-48941873da60.jpg) OBb 3th image
![2015-03-29_00325](https://cloud.githubusercontent.com/assets/11538773/6886529/9f174822-d640-11e4-9d73-90609b0cc230.jpg) Train parts get divided when you go to the top of the train and you stay at the back of it then it blocks the train carriage from moving
![2015-03-29_00326](https://cloud.githubusercontent.com/assets/11538773/6886528/9f1647d8-d640-11e4-8070-3fd45f1aef2b.jpg) Same

**Comment by billionlioe** [comment]
Well I just solved most of the map related bugs listed here (hopefully). Thank you for your time and wonderfully detailed list.
