### ISSUE TITLE
Losing hands

### ISSUE THREAD

**Issue by Wazanator** [ZPSNMRiHIssues/nmrihissues#723]
If you take a weapon and drop it you lose your hand weapon so you can no longer push zombies or take pills, etc. http://steamcommunity.com/app/224260/discussions/3/618459405715479414/

https://www.youtube.com/watch?v=Edv10v9l_iY

**Comment by CheetahPoizon** [comment]
Version:
- 1.0.9.4

What happens:
- first person camera: no viewmodel (no hands, no push, no fistfight)
- third person camera: T-pose animation

When does it happen:
- drop your latest gun but keep the medical items (bandages/pills/medkit)

Steps to reproduce the issue (How did you do it?):
- pick up bandages/pills/medkit
- pick up any gun
- drop your gun

Youtube:
- https://www.youtube.com/watch?v=IvV6kOZFoqk
(note: not mirror bug)

Idea:
- you can equip all medical items, but if you don't need it, the text says "you don't need to ..."
