### ISSUE TITLE
Flares don't spawn

### ISSUE THREAD

**Issue by CheetahPoizon** [ZPSNMRiHIssues/nmrihissues#724]
Version:
- 1.0.9.4

What happens:
- flares don't spawn

When does it happen:
- when there is a flare on the map

Steps to reproduce the issue (How did you do it?):
- nmo_junction > spawn shop > http://i.imgur.com/ng47J76.jpg
- nmo_toxteth > basement place > http://i.imgur.com/Vcb7UpR.jpg
- hammer editor > random_spawner > ammobox_flare

Youtube:
- https://www.youtube.com/watch?v=4GipQI-xyC8

Note:
- it's not a map bug

**Comment by billionlioe** [comment]
Confirmed, flares cant be spawned except via givecurrentammo

**Comment by essbuh** [comment]
works fine in dev build
