### ISSUE TITLE
Items stucking in textures and fly out(1.09.4)

### ISSUE THREAD

**Issue by AtheistNMRiH** [ZPSNMRiHIssues/nmrihissues#728]
![nms_campblood0000](https://cloud.githubusercontent.com/assets/11333747/7414866/36181824-ef77-11e4-8e41-f79fcb2237c7.jpg)
Its not only here. On many maps items spawn in shelfs, cabinets and e.t.c

**Comment by X-rock-X** [comment]
That's only happening for medical items, I did something with their world models.

I'll try to solve it.

**Comment by Fersigal** [comment]
This also happens at the medkit box in the cleopas mall "Samco"

**Comment by AtheistNMRiH** [comment]
looks like it is fixed now
