### ISSUE TITLE
nms_ransack and nms_isolated stuck at 56 zombies only every wave.

### ISSUE THREAD

**Issue by X-rock-X** [ZPSNMRiHIssues/nmrihissues#729]
After playing for a while, if you reach wave 3 on any of these maps, zombie count will be 56.

Any wave after that will have the zombie count still stuck to 56 and not increasing.

**Comment by Smil3yRiley** [comment]
Lou essentially toned down the # of zombies that would get added to each successive wave in his two maps, this'll get resolved

**Comment by lousaffire** [comment]
thanks rock!,i toned it down a bit but didn't realize it had capped at 56 :S i'll get that fixed asap, is there a hotfix planned anytime soon

**Comment by Smil3yRiley** [comment]
Yes, sometime on the 20th or the 25th

**Comment by TeXnoFile** [comment]
Lou if possible please DO NOT tone it down, ransack is one of the few maps which is actually a bit challening and fun to play, please be so kind.
