### ISSUE TITLE
Character animation issue

### ISSUE THREAD

**Issue by TeXnoFile** [ZPSNMRiHIssues/nmrihissues#736]
Version: nmrih 1.9.4
What happens: Player´s animation gets stuck in the default position 
When does it happen+steps to reproduce it: When your health is FULL and you have medkit/bandage with certain weapon in your inventory and you decide to throw the weapon away, you will get that weird position (see screenshots below). When in 1st person , you are not able to see your fists
Screenshots:
![timejttwist](https://cloud.githubusercontent.com/assets/12586797/7798070/5ed95660-02f5-11e5-94bb-82c94d344b6e.png)

**Comment by AtheistNMRiH** [comment]
This bug was posted: https://github.com/ZPSNMRiHIssues/nmrihissues/issues/723

**Comment by TeXnoFile** [comment]
Oh, im sorry, should i delete it ?

**Comment by AtheistNMRiH** [comment]
Dont know, maybe
