### ISSUE TITLE
Bug Report: Ability to kill teammates, whilst friendly-fire is disabled.

### ISSUE THREAD

**Issue by GriefMoDz** [ZPSNMRiHIssues/nmrihissues#740]
Version:
Official Steam Release / v1.0.9.4

What happens:
I've noticed that players still alive and healthy sometimes tend to be able to kill team-mates with any sort of weaponry, whilst friendly-fire is disabled. This has happened not only once, but multiple times.

When does it happen:
There isn't really an answer as to when this occurs, but all I can say is it jumps in once in a while.

Steps to reproduce the issue (How did you do it?):
To be honest, I haven't found any steps to reproduce this issue, so I've contacted you for an answer.

Screenshots:
Nothing much to show from as this is pretty self-explanatory.

Developer Console Output:
` GriefMoDz has attacked a teammate
Player gab314 died at the hands of GriefMoDz.
[Stats] -25 points (189) for killing a teammate!
[SM] Friendly Fire is disabled `

System Information:
> OS: Windows 8.1
> Processor: Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz  2.50GHz
> Installed Memory (RAM): 8.00 GB
> System Type: 64-bit Operating System, x64-based processor

Thanks, and I'm more than interested into tracking down the bug with the team (if needed)!

**Comment by AtheistNMRiH** [comment]
Maybe he was infected? If your teammate is infected, you can kill him without friendly fire

**Comment by GriefMoDz** [comment]
@AtheistNMRiH Of course, you are right about that. But as to what I'm stating, players "alive" can kill another person who is also "alive", whilst friendly-fire is disabled.

**Comment by Fersigal** [comment]
Could you name the server's IP or does it occur on all servers

**Comment by GriefMoDz** [comment]
@Fersigal There isn't a need to specify the server's IP Address, as it does occur on all servers, as from what I've seen. But, from that time when I found the issue, I was on my own server.

**Comment by TeXnoFile** [comment]
You can NOT kill the player on the server when he is NOT infected. The ones you saw must have been infected for sure.

**Comment by Bubka3** [comment]
If friendly fire is disabled it only prevents non-infected teammates from killing each other. If the person is infected, they can can still be teamkilled, regardless of the cvar.

This is currently intended behavior. We're open to suggestions on any of forums. Not a bug.
