### ISSUE TITLE
Users can use kits, bandages, and pills w/o consuming the item.

### ISSUE THREAD

**Issue by ktsuttlemyre** [ZPSNMRiHIssues/nmrihissues#742]
It seems you have two checks for deleting used items from the inventory. Unfortunately I believe I have found a way to use health status items without them being removed from the game.

If you use any health status items there is a small delay between applying the new status and deleting the item from inventory. If a user scrolls the mouse wheel right after using the item the status is applied but the item is not deleted from inventory. Then the user must quickly drop the item (clicking on the item in the inventory) and wait about 5 to 10 seconds and they can pick it back up again. If the user only scrolls the mouse wheel the item will still get deleted on what seems to be a second check by the game. But, as I mentioned before, the second delete check can be avoided by dropping the item.

**Comment by justarandomguylol** [comment]
Wow this need to be fixed ASAP :O

**Comment by essbuh** [comment]
fixed in dev build
