### ISSUE TITLE
When attempting to kick someone in game 

### ISSUE THREAD

**Issue by Fersigal** [ZPSNMRiHIssues/nmrihissues#747]
When you try to kick someone in game only numbers appear instead of a name in the vote menu. You cannot identify any person and it turns on a possibility for griefers to kick random players for no reason and then to leave the server.
![2015-07-30_00001](https://cloud.githubusercontent.com/assets/11538773/8984780/2597c75c-36d4-11e5-98ba-d31ddf47f4a5.jpg)
![2015-07-30_00002](https://cloud.githubusercontent.com/assets/11538773/8984785/29f35974-36d4-11e5-9906-7a395710ee1c.jpg)
In these pictures it's the number 6 as example

**Comment by AtheistNMRiH** [comment]
Just write   status   in dev console

**Comment by Fersigal** [comment]
I know about that one but the average Nmrih player doesn't
It's OK if you know who's gonna get kicked but the average player can't solve who it is and will just do a 50-50 gamble without knowing who they're gonna kick

**Comment by X-rock-X** [comment]
We will take a look at this. Thanks.
