### ISSUE TITLE
Ammo checking while in ironsight mode w/ Sako 85 Ironsights causes scope overlay to show up

### ISSUE THREAD

**Issue by Smil3yRiley** [ZPSNMRiHIssues/nmrihissues#749]
Complicated title but the steps to reproduce this are more straightforward

----

* Spawn fa_sako85_ironsights
* Equip
* Go into ironsights mode
* Ammo check 

The scope overlay should then appear

**Comment by Smil3yRiley** [comment]
As an added note it's on r8542 in the dev build

**Comment by X-rock-X** [comment]
Issue addressed, EZ PZ.
