### ISSUE TITLE
floating walkie talkie

### ISSUE THREAD

**Issue by x5566asd** [ZPSNMRiHIssues/nmrihissues#756]
![2015-09-27_00001](https://cloud.githubusercontent.com/assets/11902227/10121133/0bd0db96-6510-11e5-8843-f3416e804316.jpg)

1.09.5
when someone equip a walkie talkie, the model floating in air instead of the proper position.

new animation bug

**Comment by Bubka3** [comment]
Confirmed, missing a bone. Rock is working on it.

**Comment by X-rock-X** [comment]
Fixed issue.
