### ISSUE TITLE
Death Cam bug

### ISSUE THREAD

**Issue by Fersigal** [ZPSNMRiHIssues/nmrihissues#769]
When dying you can pick up your weapons when the death cam is on for let's say 5 - 10 seconds
After that you can drop only Weapons, melee and Explosives (no ammo in The ammo slot)
![2015-10-27_00001](https://cloud.githubusercontent.com/assets/11538773/10766443/e70f30f2-7cd7-11e5-8f4e-2dd349930c53.jpg)
First picture is my inventory shown
![2015-10-27_00002](https://cloud.githubusercontent.com/assets/11538773/10766447/eafb4660-7cd7-11e5-99d1-d6062ca15e40.jpg)
This is my inventory shown with flashlight
![2015-10-27_00003](https://cloud.githubusercontent.com/assets/11538773/10766451/ef21ffea-7cd7-11e5-9d57-5251ec1e22fa.jpg)
you can pick up ur items now
![2015-10-27_00004](https://cloud.githubusercontent.com/assets/11538773/10766452/ef365e5e-7cd7-11e5-9832-6ad808c10712.jpg)
and drop em wherever you like
![2015-10-27_00005](https://cloud.githubusercontent.com/assets/11538773/10766453/ef44de3e-7cd7-11e5-9bff-9d988c596301.jpg)
That's it basically
Map: Nmo_theater

**Comment by essbuh** [comment]
fixed in dev build
