### ISSUE TITLE
Beta 1.09.5 nms_midwest is broken

### ISSUE THREAD

**Issue by AtheistNMRiH** [ZPSNMRiHIssues/nmrihissues#774]
![nms_midwest0001](https://cloud.githubusercontent.com/assets/11333747/11650041/d51a85c6-9db7-11e5-84ab-1dce6b3fff7c.jpg)
![nms_midwest0002](https://cloud.githubusercontent.com/assets/11333747/11650042/d51aa04c-9db7-11e5-80d0-72579aae70c6.jpg)
![nms_midwest0003](https://cloud.githubusercontent.com/assets/11333747/11650043/d51d36fe-9db7-11e5-9375-bc74b57c03b2.jpg)
![nms_midwest0004](https://cloud.githubusercontent.com/assets/11333747/11650044/d51fa7c2-9db7-11e5-8e40-d3d32de49567.jpg)
Train doesnt work. Zombies dont spawn, zones dont show. Player clips doesnt work. Boards dont shows

**Comment by Bubka3** [comment]
(patch 2)

**Comment by Smil3yRiley** [comment]
Well shit

**Comment by billionlioe** [comment]
Oh fuck. Dang it visgroups, you failed me again! Will fix ASAP.

**Comment by Bubka3** [comment]
confirmed fix r8558
