### ISSUE TITLE
1.09.5 nmo_cleopas(env_cubemaps?)

### ISSUE THREAD

**Issue by AtheistNMRiH** [ZPSNMRiHIssues/nmrihissues#775]
looks like something with cubemaps
![nmo_cleopas0000](https://cloud.githubusercontent.com/assets/11333747/11862885/fb52fc80-a4c1-11e5-9534-7fa7867aef22.jpg)
![nmo_cleopas0001](https://cloud.githubusercontent.com/assets/11333747/11862886/fb549298-a4c1-11e5-8c68-28123278b6b5.jpg)
![nmo_cleopas0002](https://cloud.githubusercontent.com/assets/11333747/11862887/fb562a22-a4c1-11e5-843d-ab1dc596c3fe.jpg)

**Comment by Smil3yRiley** [comment]
Should be fixed
