### ISSUE TITLE
[1.09.5] Player can't read vote menu. and When player vote, it was decided immediately

### ISSUE THREAD

**Issue by yomox9** [ZPSNMRiHIssues/nmrihissues#780]
I can't read vote menu, But I could select vote.
Environment : NMRiH 1.09.5
server = linux, without Metamod/Sourcemod. Client = windows7
![2015-12-20_00002](https://cloud.githubusercontent.com/assets/14893069/11913727/848125c2-a6b1-11e5-929a-e30ef8483b1c.jpg)

**Comment by AtheistNMRiH** [comment]
++++++

**Comment by Smil3yRiley** [comment]
Looks to be a side effect from security fixes, will be fixed

**Comment by Smil3yRiley** [comment]
For now if you're using SM or Metamod, you can disable the default vote menu with sv_allow_votes 0

**Comment by yomox9** [comment]
thx. I already set it.

**Comment by Smil3yRiley** [comment]
Potentially fixed in revision 8566
