### ISSUE TITLE
[1.9.5]Voting system is broken

### ISSUE THREAD

**Issue by TeXnoFile** [ZPSNMRiHIssues/nmrihissues#787]
**Version**: Nmrih 1.9.5

There is a bug in the voting system. Players are **unable** to see the items on left but they **can** call a vote to kick/change map/restart or set the next map. Other players can not do anything about it. If one decides to kick/change the map etc. **it will happen without the need of other people to vote for it** (see the screenshots below).

It is happening on every single server **regadless** of the voting config (disabled/enabled).

Steps to reporoduce: Spawn (luckily, spectators still can not vote)-> call a vote-> click on player name-> boom, player is kicked/map is changed immediately
![1](https://cloud.githubusercontent.com/assets/12586797/12119927/d1a639b2-b3ce-11e5-98a2-912d2e02b268.jpg)
![2](https://cloud.githubusercontent.com/assets/12586797/12119934/d8a35042-b3ce-11e5-9251-1530bf41cc24.jpg)
![3](https://cloud.githubusercontent.com/assets/12586797/12119939/de12037a-b3ce-11e5-9110-c4b1d6e03618.jpg)

**Comment by AtheistNMRiH** [comment]
same as https://github.com/ZPSNMRiHIssues/nmrihissues/issues/780

**Comment by TeXnoFile** [comment]
OH sorry, my bad....i didnt see it cuz it was in closed section.
