### ISSUE TITLE
Nmo_brooklyn (not done, hidden option not possible ¯\_(ツ)_/¯)

### ISSUE THREAD

**Issue by Fersigal** [ZPSNMRiHIssues/nmrihissues#802]
NOT SORTED
![20160420122831_1](https://cloud.githubusercontent.com/assets/11538773/14674382/669e5b0c-0704-11e6-8668-8869e4b15574.jpg)
![20160420123045_1](https://cloud.githubusercontent.com/assets/11538773/14674381/669d59d2-0704-11e6-82c9-e6a302ae6243.jpg)
![20160420123213_1](https://cloud.githubusercontent.com/assets/11538773/14674383/66b10298-0704-11e6-9b41-e9ba9a8812da.jpg)
![20160420123747_1](https://cloud.githubusercontent.com/assets/11538773/14674384/66b17c50-0704-11e6-95ab-14a2b780a83c.jpg)
![20160420123841_1](https://cloud.githubusercontent.com/assets/11538773/14674385/66c407da-0704-11e6-8584-1e1f6bce8105.jpg)
![20160420123846_1](https://cloud.githubusercontent.com/assets/11538773/14674386/66c6ed74-0704-11e6-93ba-1971bb096a9e.jpg)
![20160420124011_1](https://cloud.githubusercontent.com/assets/11538773/14674387/66d73a8a-0704-11e6-80c6-56e46f22d6b3.jpg)
![20160420124039_1](https://cloud.githubusercontent.com/assets/11538773/14674388/66d9a75c-0704-11e6-8be3-e2250cb3c6e0.jpg)
![20160420124307_1](https://cloud.githubusercontent.com/assets/11538773/14674391/66fb5a28-0704-11e6-94b9-166c80c62f03.jpg)
![20160420124354_1](https://cloud.githubusercontent.com/assets/11538773/14674389/66ea1e16-0704-11e6-85b7-2bd5055e9e65.jpg)
![20160420124430_1](https://cloud.githubusercontent.com/assets/11538773/14674390/66eeade6-0704-11e6-9f5f-bddcaa6072f0.jpg)
![20160420124512_1](https://cloud.githubusercontent.com/assets/11538773/14674392/66fcefe6-0704-11e6-9d9d-deb11c5b306a.jpg)
![20160420124545_1](https://cloud.githubusercontent.com/assets/11538773/14674393/67053c6e-0704-11e6-9afa-8f0872b11dc4.jpg)
![20160420124722_1](https://cloud.githubusercontent.com/assets/11538773/14674396/671b9df6-0704-11e6-8f06-39b3e5a5ee37.jpg)
![20160420125051_1](https://cloud.githubusercontent.com/assets/11538773/14674394/67160a6c-0704-11e6-8eab-6f661986ecbc.jpg)
![20160420125255_1](https://cloud.githubusercontent.com/assets/11538773/14674395/67184d7c-0704-11e6-81fe-b1d8b7685872.jpg)
![20160420125505_1](https://cloud.githubusercontent.com/assets/11538773/14674397/67294bae-0704-11e6-9a9d-3299eebd240c.jpg)
![20160420125513_1](https://cloud.githubusercontent.com/assets/11538773/14674398/672b550c-0704-11e6-827b-ae9fbd03ec9a.jpg)
![20160420125558_1](https://cloud.githubusercontent.com/assets/11538773/14674399/6735c2a8-0704-11e6-81fc-4f8394cb0057.jpg)
![20160420125653_1](https://cloud.githubusercontent.com/assets/11538773/14674400/673c8e8a-0704-11e6-93fd-f6dc91e7a88b.jpg)
![20160420131801_1](https://cloud.githubusercontent.com/assets/11538773/14674401/673e0df0-0704-11e6-8606-0564f7d7e3d5.jpg)
![20160420132004_1](https://cloud.githubusercontent.com/assets/11538773/14674402/6749bf56-0704-11e6-9578-810ee63648e9.jpg)
![20160420132144_1](https://cloud.githubusercontent.com/assets/11538773/14674403/674eeec2-0704-11e6-8932-5d4e7da95a94.jpg)
![20160420132722_1](https://cloud.githubusercontent.com/assets/11538773/14674404/6750d1ce-0704-11e6-917b-c8993e13d789.jpg)
![20160420133159_1](https://cloud.githubusercontent.com/assets/11538773/14674405/675fb69e-0704-11e6-9d23-60a5d40237cf.jpg)
![20160420133245_1](https://cloud.githubusercontent.com/assets/11538773/14674406/676368de-0704-11e6-9df4-52451728b59d.jpg)
![20160420133425_1](https://cloud.githubusercontent.com/assets/11538773/14674407/676571ec-0704-11e6-967a-15005f13f23d.jpg)
![20160420133729_1](https://cloud.githubusercontent.com/assets/11538773/14674408/677368b0-0704-11e6-92c6-610c64c701dc.jpg)
![20160420133755_1](https://cloud.githubusercontent.com/assets/11538773/14674409/6779514e-0704-11e6-95b3-d0c2336c6a21.jpg)
![20160420133831_1](https://cloud.githubusercontent.com/assets/11538773/14674410/677c18f2-0704-11e6-8c32-eb11373b8d01.jpg)
![20160420133918_1](https://cloud.githubusercontent.com/assets/11538773/14674411/6789745c-0704-11e6-994b-8e21d278ca53.jpg)
![20160420134005_1](https://cloud.githubusercontent.com/assets/11538773/14674413/6790c2f2-0704-11e6-8c97-83818a12aaac.jpg)
![20160420134102_1](https://cloud.githubusercontent.com/assets/11538773/14674412/678f638a-0704-11e6-8ab4-bebc88084ccc.jpg)
![20160420134129_1](https://cloud.githubusercontent.com/assets/11538773/14674414/679c41ae-0704-11e6-8739-5fe3120a9724.jpg)
![20160420134524_1](https://cloud.githubusercontent.com/assets/11538773/14674415/67a730aa-0704-11e6-8517-e4ae1a7d163e.jpg)
![20160420134607_1](https://cloud.githubusercontent.com/assets/11538773/14674416/67a912d0-0704-11e6-8b77-6780f4063c5e.jpg)
![20160420134612_1](https://cloud.githubusercontent.com/assets/11538773/14674417/67b3269e-0704-11e6-8e7e-577841b65518.jpg)
![20160420134622_1](https://cloud.githubusercontent.com/assets/11538773/14674418/67ba6a9e-0704-11e6-93aa-d8f473f2daed.jpg)
![20160420134643_1](https://cloud.githubusercontent.com/assets/11538773/14674420/67c05030-0704-11e6-89f6-870009301030.jpg)
![20160420135040_1](https://cloud.githubusercontent.com/assets/11538773/14674421/67c5e52c-0704-11e6-966d-319cbcb53063.jpg)
![20160420135055_1](https://cloud.githubusercontent.com/assets/11538773/14674422/67ce0d92-0704-11e6-9eed-9687d0f668b2.jpg)
![20160420135155_1](https://cloud.githubusercontent.com/assets/11538773/14674423/67d72954-0704-11e6-899d-ca85fa0b6883.jpg)
![20160420135206_1](https://cloud.githubusercontent.com/assets/11538773/14674424/67da4db4-0704-11e6-9d2c-0dc617703301.jpg)
![20160420135304_1](https://cloud.githubusercontent.com/assets/11538773/14674425/67e0cfe0-0704-11e6-8d02-35650225386d.jpg)
![20160420135357_1](https://cloud.githubusercontent.com/assets/11538773/14674426/67e9b63c-0704-11e6-81e8-5a6bb47cd991.jpg)
![20160420135421_1](https://cloud.githubusercontent.com/assets/11538773/14674427/67edccb8-0704-11e6-84f7-b7fde47d6fdd.jpg)
![20160420135442_1](https://cloud.githubusercontent.com/assets/11538773/14674428/67f5b9e6-0704-11e6-9803-5d84b9135934.jpg)
![20160420135519_1](https://cloud.githubusercontent.com/assets/11538773/14674429/67fc867c-0704-11e6-9af2-d267192f7d0e.jpg)
![20160420135549_1](https://cloud.githubusercontent.com/assets/11538773/14674430/68013686-0704-11e6-824b-906690487442.jpg)
![20160420135637_1](https://cloud.githubusercontent.com/assets/11538773/14674431/680add62-0704-11e6-84ee-22605c530889.jpg)
![20160420135747_1](https://cloud.githubusercontent.com/assets/11538773/14674432/6813b43c-0704-11e6-8ef9-5013ceb37d0f.jpg)
![20160420135813_1](https://cloud.githubusercontent.com/assets/11538773/14674433/68180dfc-0704-11e6-9f89-42d7e58e541e.jpg)
![20160420135829_1](https://cloud.githubusercontent.com/assets/11538773/14674434/68214c64-0704-11e6-8710-98ca37a6156b.jpg)
![20160420135905_1](https://cloud.githubusercontent.com/assets/11538773/14674437/68280e0a-0704-11e6-8074-fc479a1af6d1.jpg)
![20160420135924_1](https://cloud.githubusercontent.com/assets/11538773/14674435/68214f98-0704-11e6-87fd-c2a2786e0894.jpg)
![20160420135958_1](https://cloud.githubusercontent.com/assets/11538773/14674436/68265812-0704-11e6-8c8d-932ae4505c58.jpg)
![20160420140049_1](https://cloud.githubusercontent.com/assets/11538773/14674438/6833ae4a-0704-11e6-9f8d-a01dd3b7da7f.jpg)
![20160420140334_1](https://cloud.githubusercontent.com/assets/11538773/14674440/68392154-0704-11e6-9bb3-a4b7235aa23c.jpg)
![20160420140413_1](https://cloud.githubusercontent.com/assets/11538773/14674439/6835255e-0704-11e6-93fc-5778f336d023.jpg)
![20160420140521_1](https://cloud.githubusercontent.com/assets/11538773/14674441/683b2832-0704-11e6-80e4-85e077dfd5fc.jpg)
![20160420140612_1](https://cloud.githubusercontent.com/assets/11538773/14674442/683bdc28-0704-11e6-879d-8e6e2cc3fe2e.jpg)
![20160420140618_1](https://cloud.githubusercontent.com/assets/11538773/14674443/6848b696-0704-11e6-994b-d074bcde539c.jpg)
![20160420140647_1](https://cloud.githubusercontent.com/assets/11538773/14674444/6849e318-0704-11e6-8703-961181151e4a.jpg)
![20160420140832_1](https://cloud.githubusercontent.com/assets/11538773/14674445/684c10a2-0704-11e6-9e35-1c14a95c68df.jpg)
![20160420140940_1](https://cloud.githubusercontent.com/assets/11538773/14674446/684ed706-0704-11e6-8f86-b6decae75323.jpg)
![20160420141101_1](https://cloud.githubusercontent.com/assets/11538773/14674447/684f47a4-0704-11e6-88a1-633050f0207b.jpg)
![20160420141120_1](https://cloud.githubusercontent.com/assets/11538773/14674450/6860374e-0704-11e6-8055-4021946753f2.jpg)
![20160420141212_1](https://cloud.githubusercontent.com/assets/11538773/14674448/685e78d2-0704-11e6-8670-89cdd0a3ccad.jpg)
![20160420141238_1](https://cloud.githubusercontent.com/assets/11538773/14674449/685f4564-0704-11e6-91ed-d85672e14513.jpg)
![20160420141324_1](https://cloud.githubusercontent.com/assets/11538773/14674451/6861aa98-0704-11e6-9f86-b75fe546fe93.jpg)
![20160420141334_1](https://cloud.githubusercontent.com/assets/11538773/14674452/6862b384-0704-11e6-866a-2df6f1ef983b.jpg)
![20160420141404_1](https://cloud.githubusercontent.com/assets/11538773/14674456/6885f240-0704-11e6-99f0-60e91cc7dbe5.jpg)
![20160420141428_1](https://cloud.githubusercontent.com/assets/11538773/14674457/688631ec-0704-11e6-81e3-919df3446a54.jpg)
![20160420141441_1](https://cloud.githubusercontent.com/assets/11538773/14674454/688552ea-0704-11e6-9848-ad26b17b7118.jpg)
![20160420141449_1](https://cloud.githubusercontent.com/assets/11538773/14674455/6885e232-0704-11e6-858e-1f00db2d10b7.jpg)
![20160420141458_1](https://cloud.githubusercontent.com/assets/11538773/14674458/68893fae-0704-11e6-8e2c-3a65b09c909a.jpg)
![20160420141520_1](https://cloud.githubusercontent.com/assets/11538773/14674462/68a822d4-0704-11e6-9339-a8e72571c0c1.jpg)
![20160420141608_1](https://cloud.githubusercontent.com/assets/11538773/14674459/68a48d68-0704-11e6-9bab-b8a74f2f2b02.jpg)
![20160420141623_1](https://cloud.githubusercontent.com/assets/11538773/14674461/68a70e76-0704-11e6-8522-6f00aa634d0b.jpg)
![20160420141633_1](https://cloud.githubusercontent.com/assets/11538773/14674460/68a61066-0704-11e6-823d-75818c7373e3.jpg)
![20160420141737_1](https://cloud.githubusercontent.com/assets/11538773/14674463/68aa630a-0704-11e6-9b0a-7f0623a6bbd1.jpg)
![20160420141832_1](https://cloud.githubusercontent.com/assets/11538773/14674464/68b8871e-0704-11e6-8fbf-ad8a9e1c6d27.jpg)
![20160420141910_1](https://cloud.githubusercontent.com/assets/11538773/14674465/68b94550-0704-11e6-8226-b87682ce3053.jpg)

**Comment by Fersigal** [comment]
Other "fixed" maps will follow

**Comment by yomox9** [comment]
What is this?
Did you read following?
https://github.com/ZPSNMRiHIssues/nmrihissues

**Comment by Fersigal** [comment]
so for every damn little issue i should write how to recreate. Interesting to see how you actually have no clue about what i have been doing this whole time..... *facepalm*

**Comment by Mateos81** [comment]
Readme.md: A short title, describing the issue. e.g. "Can't use X on nms_isolated"
Your title: Nmo_brooklyn (not sorted)
Diagnostic: Totally not explaining the issue, if there is any.

Readme.md: A detailed summary including [...]
You summary: NOT SORTED
Diagnostic: Even better than the title...

I'd be a dev, this would be already closed... Perhaps pull your fingers out of your butt and explain what are these pictures referring to? Perhaps item misplacement?

**Comment by AtheistNMRiH** [comment]
But he already made something like that, and some of bugs(like on fema, chinatown, toxteth) were fixed.
I think he will sort it, just haven't time now or something else.

**Comment by Fersigal** [comment]
@matteos81
You sound like these people fingerpointing at people without even knowing what they're referring to. Most unlike you i have actually posted something useful and most unlike you i have ACTUALLY PUT TIME INTO DOING IT SO. This is not a place to start a fight and i find it very immature that people start fingerpointing at people for something they have no original experience with. So please if you want to start a fight go on reddit.

**Comment by Mateos81** [comment]
The main thing I pointed is that to the question of @yomox9 you replied by a facepalm instead of taking the time to explain what you were doing... If that ticket is linked to other ones, then put a mention of them here, that would help understanding.

Now, I've been following this game since it was a mod project, then released, then reworked as a stand-alone game, released, and to these days. I haven't counted the hours I've put in it, I did also report stuff when it was still a mod.

As a dev myself, when reading your reply to @yomox9, I thought the same as you're thinking of me, and couldn't resist reacting :) They have opened a GitHub to fill issues and they've taken the time to write a readme explaining how to fill a bug report, you've not respected it, and you're complaining about a reaction, as if everyone here should have every past ticket in mind... I hope you see my point.

Finally yes GitHub isn't a place to start up a fight (perhaps on the way fixing stuff, but that's a dev matter).

**Comment by Fersigal** [comment]
Sorry for the misunderstandment, but you have to realize that i actually put a lot of effort in actually making all of this and i can't just address the problem if i'm in a busy time schedule. At the moment i have little space to breathe cause of the latter of pressure that's on my shoulders.

**Comment by lousaffire** [comment]
If you don't have enough time to feedback properly, testing for bugs may not be for you. And if you think what you've done takes effort, try building something, or fixing something and see how much effort and time it takes, on top of our own pressures.Maybe other devs find your posts useful, but I have no use for a wall of jpegs, and i'm pretty sure we've have had this chat before.

**Comment by Fersigal** [comment]
.... Only 4 words can describe this matter: do it by yourself !

**Comment by lousaffire** [comment]
Only 4 words can describe your threads, waste of my time.

**Comment by Fersigal** [comment]
git commit --amend
